name: Test

# Run this workflow every time a new commit pushed to your repository
on: [push]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test:
    # Name the Job
    name: python unittest
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Prepare repo
        uses: actions/checkout@master

      # Runs the Super-Linter action
      - name: Test
        uses: onichandame/python-test-action@master
